// Code generated by go2go; DO NOT EDIT.


//line future.go2:1
package future

import (
	"sync/atomic"
	"runtime"
)

//line future.go2:6
type Importable୦ int
//line future.go2:6
type _ atomic.Value
//line future.go2:6
type _ runtime.BlockProfileRecord
