// Code generated by go2go; DO NOT EDIT.


//line future_test.go2:1
package future

import (
	"testing"
	"time"
)

func TestFuture(t *testing.T) {
	s := "done"
	f := instantiate୦୦Future୦string{}

	go func() {
		time.Sleep(time.Second)
		f.Put(s)
	}()

	if f.Get() != s {
		t.Fatalf("future failed")
	}
}

//line future_test.go2:20
type instantiate୦୦Future୦string struct {
//line future.go2:9
 value atomic.Value
}

//line future.go2:13
func (f *instantiate୦୦Future୦string,) Get() string {
	var v interface{}
	for ; v == nil; v = f.value.Load() {
		runtime.Gosched()
	}
	return v.(string)
}

func (f *instantiate୦୦Future୦string,) Put(v string,

//line future.go2:21
) {
	f.value.Store(interface{}(v))
}

//line future.go2:23
type _ testing.B

//line future.go2:23
const _ = time.ANSIC
