// Code generated by go2go; DO NOT EDIT.


//line future.go2:5
package future

//line future.go2:5
import (
//line future.go2:5
 "runtime"
//line future.go2:5
 "sync/atomic"
//line future.go2:5
 "testing"
//line future.go2:5
 "time"
//line future.go2:5
)

//line future.go2:5
type Importable୦ int

//line future.go2:5
var _ = runtime.BlockProfile
//line future.go2:5
var _ = atomic.AddInt32
//line future.go2:5
var _ = testing.AllocsPerRun

//line future.go2:5
const _ = time.ANSIC
