// Code generated by go2go; DO NOT EDIT.


//line main.go2:1
package main

//line main.go2:9
func main() {
			a := map[string]int{}
			b := make(chan int)
			c := []string{}
//line main.go2:12
 instantiate୦୦Len୦map୮6string୮7int(a)
//line main.go2:14
 instantiate୦୦Len୦chan୮0int(b)
	instantiate୦୦Len୦୮6୮7string(c)
//line main.go2:17
}
//line main.go2:7
func instantiate୦୦Len୦map୮6string୮7int(t map[string]int,) {}
//line main.go2:7
func instantiate୦୦Len୦chan୮0int(t chan int,)              {}
//line main.go2:7
func instantiate୦୦Len୦୮6୮7string(t []string,)             {}

//line main.go2:7
type Importable୦ int
