// Code generated by go2go; DO NOT EDIT.


//line slices_test.go2:1
package slices

//line slices_test.go2:1
import (
//line slices_test.go2:1
 "fmt"
//line slices_test.go2:1
 "github.com/changkun/go2generics/math"
//line slices_test.go2:1
 "sort"
//line slices_test.go2:1
 "testing"
//line slices_test.go2:1
)

//line slices_test.go2:5
func TestPrint(t *testing.T) {
//line slices_test.go2:5
 instantiate୦୦Prints୦int([]int{1, 2, 3})
//line slices_test.go2:7
}

//line slices.go2:85
func instantiate୦୦Prints୦int(s []int,) {
	for _, v := range s {
		fmt.Println(v)
	}
}

//line slices.go2:89
var _ = fmt.Errorf

//line slices.go2:89
type _ math.Importable୦
//line slices.go2:89
type _ sort.Float64Slice

//line slices.go2:89
var _ = testing.AllocsPerRun
