// Code generated by go2go; DO NOT EDIT.


//line slices.go2:5
package slices

//line slices.go2:5
import (
//line slices.go2:5
 "fmt"
//line slices.go2:5
 "github.com/changkun/go2generics/math"
//line slices.go2:5
 "sort"
//line slices.go2:5
 "testing"
//line slices.go2:5
)

//line slices.go2:5
type Importable୦ int

//line slices.go2:5
var _ = fmt.Errorf

//line slices.go2:5
type _ math.Importable୦
//line slices.go2:5
type _ sort.Float64Slice

//line slices.go2:5
var _ = testing.AllocsPerRun
