// Code generated by go2go; DO NOT EDIT.


//line slices.go2:1
package slices

import (
	"fmt"

	"github.com/changkun/go2generics/contracts"
	"github.com/changkun/go2generics/math"
)

//line slices.go2:8
type Importable୦ int
//line slices.go2:8
type _ fmt.Formatter
//line slices.go2:8
type _ contracts.Importable୦
//line slices.go2:8
type _ math.Importable୦
