// Code generated by go2go; DO NOT EDIT.


//line sort.go2:1
package slices

import (
	"sort"

	"github.com/changkun/go2generics/contracts"
)

//line sort.go2:7
type _ sort.Float64Slice
//line sort.go2:7
type _ contracts.Importable୦
