// Code generated by go2go; DO NOT EDIT.


//line sort.go2:5
package slices

//line sort.go2:5
import (
//line sort.go2:5
 "github.com/changkun/go2generics/math"
//line sort.go2:5
 "sort"
//line sort.go2:5
 "testing"
//line sort.go2:5
)

//line sort.go2:5
type Importable୦ int
//line sort.go2:5
type _ math.Importable୦
//line sort.go2:5
type _ sort.Float64Slice

//line sort.go2:5
var _ = testing.AllocsPerRun
