// Code generated by go2go; DO NOT EDIT.


//line bug1.go2:1
package bugs

//line bug1.go2:54
type P struct {
	K int
	V int
}
type Q struct {
	s []P
}

func F() Q {
			var s []P

//line bug1.go2:67
 return Q{s}
}

func main() {
	F()
}

//line bug1.go2:72
type Importable୦ int
