// Code generated by go2go; DO NOT EDIT.


//line graph_test.go2:1
package graph

//line graph_test.go2:1
import "testing"

//line graph_test.go2:5
type Node struct {
	n int
}

func (n Node) Edges() []Edge {
	return nil
}

type Edge struct {
	n int
}

func (e Edge) Nodes() (from, to Node) {
	return Node{}, Node{}
}

func TestGraph(t *testing.T) {
	g := instantiate୦୦New୦graph୮aNode୦graph୮aEdge([]Node{})
	g.ShortestPath(Node{}, Node{})
}

//line graph.go2:26
func instantiate୦୦New୦graph୮aNode୦graph୮aEdge(
	nodes []Node,

//line graph.go2:27
) *instantiate୦୦Graph୦graph୮aNode୦graph୮aEdge {

	return nil
}

//line graph.go2:30
type instantiate୦୦Graph୦graph୮aNode୦graph୮aEdge struct {
//line graph.go2:23
}

//line graph.go2:34
func (g *instantiate୦୦Graph୦graph୮aNode୦graph୮aEdge,) ShortestPath(from, to Node,

//line graph.go2:34
) []Edge {

	return nil
}

//line graph.go2:37
var _ = testing.AllocsPerRun
