// Code generated by go2go; DO NOT EDIT.


//line graph.go2:5
package graph

//line graph.go2:5
import "testing"

//line graph.go2:5
type Importable୦ int

//line graph.go2:5
var _ = testing.AllocsPerRun
