// Code generated by go2go; DO NOT EDIT.


//line checker.go2:1
package math

//line checker.go2:1
import "testing"

//line checker.go2:1
type Importable୦ int

//line checker.go2:1
var _ = testing.AllocsPerRun
