// Code generated by go2go; DO NOT EDIT.


//line checker.go2:5
package math

//line checker.go2:5
import "testing"

//line checker.go2:5
type Importable୦ int

//line checker.go2:5
var _ = testing.AllocsPerRun
