// Code generated by go2go; DO NOT EDIT.


//line comp.go2:1
package math

import "github.com/changkun/go2generics/contracts"

//line comp.go2:3
type Importable୦ int
//line comp.go2:3
type _ contracts.Importable୦
