// Code generated by go2go; DO NOT EDIT.


//line value.go2:5
package atomic

//line value.go2:5
import (
//line value.go2:5
 "math/rand"
//line value.go2:5
 "runtime"
//line value.go2:5
 "sync/atomic"
//line value.go2:5
 "testing"
//line value.go2:5
)

//line value.go2:5
type Importable୦ int

//line value.go2:5
var _ = rand.ExpFloat64
//line value.go2:5
var _ = runtime.BlockProfile
//line value.go2:5
var _ = atomic.AddInt32
//line value.go2:5
var _ = testing.AllocsPerRun
