// Code generated by go2go; DO NOT EDIT.


//line value_test.go2:1
package atomic

import (
//line value_test.go2:6
 "testing"
)

func TestValue(t *testing.T) {
	var v instantiate୦୦Value୦int
	v.Store(42)
	x := v.Load()
	if x != 42 {
		t.Fatalf("wrong value: got %+v, want 42", x)
	}
	v.Store(84)
	x = v.Load()
	if x != 84 {
		t.Fatalf("wrong value: got %+v, want 84", x)
	}
}

//line value_test.go2:21
type instantiate୦୦Value୦int struct {
//line value.go2:6
 val atomic.Value
}

func (v *instantiate୦୦Value୦int,) Load() int {
	x := v.val.Load()
	return x.(int)
}

func (v *instantiate୦୦Value୦int,) Store(val int,

//line value.go2:14
) {
	v.val.Store(interface{}(val))
}

//line value.go2:16
type _ testing.B
