// Code generated by go2go; DO NOT EDIT.


//line chans.go2:5
package chans

//line chans.go2:5
import (
//line chans.go2:5
 "math/rand"
//line chans.go2:5
 "runtime"
//line chans.go2:5
 "sync"
//line chans.go2:5
 "testing"
//line chans.go2:5
)

//line chans.go2:5
type Importable୦ int

//line chans.go2:5
var _ = rand.ExpFloat64
//line chans.go2:5
var _ = runtime.BlockProfile

//line chans.go2:5
type _ sync.Cond

//line chans.go2:5
var _ = testing.AllocsPerRun
