// Code generated by go2go; DO NOT EDIT.


//line stack.go2:5
package stack

//line stack.go2:5
import "testing"

//line stack.go2:5
type Importable୦ int

//line stack.go2:5
var _ = testing.AllocsPerRun
