// Code generated by go2go; DO NOT EDIT.


//line stack.go2:1
package stack

//line stack.go2:1
import "testing"

//line stack.go2:1
type Importable୦ int

//line stack.go2:1
var _ = testing.AllocsPerRun
