// Code generated by go2go; DO NOT EDIT.


//line strings.go2:1
package strings

//line strings.go2:1
import (
//line strings.go2:1
 "fmt"
//line strings.go2:1
 "reflect"
//line strings.go2:1
 "testing"
//line strings.go2:1
)

//line strings.go2:5
type Stringer interface {
	String() string
}
//line strings.go2:7
type Importable୦ int

//line strings.go2:7
var _ = fmt.Errorf
//line strings.go2:7
var _ = reflect.Append
//line strings.go2:7
var _ = testing.AllocsPerRun
