// Code generated by go2go; DO NOT EDIT.


//line strings.go2:5
package strings

//line strings.go2:5
import (
//line strings.go2:5
 "fmt"
//line strings.go2:5
 "reflect"
//line strings.go2:5
 "testing"
//line strings.go2:5
)

//line strings.go2:10
type Stringer interface {
	String() string
}
//line strings.go2:12
type Importable୦ int

//line strings.go2:12
var _ = fmt.Errorf
//line strings.go2:12
var _ = reflect.Append
//line strings.go2:12
var _ = testing.AllocsPerRun
