// Code generated by go2go; DO NOT EDIT.


//line printer.go2:1
package fmt

//line printer.go2:1
import (
//line printer.go2:1
 "fmt"
//line printer.go2:1
 "testing"
//line printer.go2:1
)

//line printer.go2:1
type Importable୦ int

//line printer.go2:1
var _ = fmt.Errorf
//line printer.go2:1
var _ = testing.AllocsPerRun
