// Code generated by go2go; DO NOT EDIT.


//line printer_test.go2:1
package fmt

//line printer_test.go2:1
import (
//line printer_test.go2:1
 "fmt"
//line printer_test.go2:1
 "testing"
//line printer_test.go2:1
)

//line printer_test.go2:5
func TestPrint(t *testing.T) {
//line printer_test.go2:5
 instantiate୦୦Print୦int([]int{1, 2, 3})
//line printer_test.go2:7
}
//line printer.go2:7
func instantiate୦୦Print୦int(s []int,) {
	for _, v := range s {
		fmt.Println(v)
	}
}

//line printer.go2:11
var _ = fmt.Errorf
//line printer.go2:11
var _ = testing.AllocsPerRun
