// Code generated by go2go; DO NOT EDIT.


//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
package maps

//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
import (
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
 "github.com/changkun/go2generics/chans"
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
 "math/rand"
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
 "runtime"
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
 "sync"
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
 "testing"
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
)

//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
type Importable୦ int
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
type _ chans.Importable୦

//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
var _ = rand.ExpFloat64
//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
var _ = runtime.BlockProfile

//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
type _ sync.Cond

//line /Users/changkun/dev/go2path/src/github.com/changkun/go2generics/maps/maps.go2:2
var _ = testing.AllocsPerRun
