// Code generated by go2go; DO NOT EDIT.


//line maps.go2:2
package maps

//line maps.go2:2
import (
//line maps.go2:2
 "github.com/changkun/go2generics/chans"
//line maps.go2:2
 "math/rand"
//line maps.go2:2
 "runtime"
//line maps.go2:2
 "sync"
//line maps.go2:2
 "testing"
//line maps.go2:2
)

//line maps.go2:2
type Importable୦ int
//line maps.go2:2
type _ chans.Importable୦

//line maps.go2:2
var _ = rand.ExpFloat64
//line maps.go2:2
var _ = runtime.BlockProfile

//line maps.go2:2
type _ sync.Cond

//line maps.go2:2
var _ = testing.AllocsPerRun
