// Code generated by go2go; DO NOT EDIT.


//line orderedmap.go2:1
package maps

//line orderedmap.go2:1
import (
//line orderedmap.go2:1
 "github.com/changkun/go2generics/chans"
//line orderedmap.go2:1
 "math/rand"
//line orderedmap.go2:1
 "runtime"
//line orderedmap.go2:1
 "sync"
//line orderedmap.go2:1
 "testing"
//line orderedmap.go2:1
)

//line orderedmap.go2:1
type Importable୦ int
//line orderedmap.go2:1
type _ chans.Importable୦

//line orderedmap.go2:1
var _ = rand.ExpFloat64
//line orderedmap.go2:1
var _ = runtime.BlockProfile

//line orderedmap.go2:1
type _ sync.Cond

//line orderedmap.go2:1
var _ = testing.AllocsPerRun
