// Code generated by go2go; DO NOT EDIT.


//line set.go2:5
package sets

//line set.go2:5
import (
//line set.go2:5
 "github.com/changkun/go2generics/math"
//line set.go2:5
 "github.com/changkun/go2generics/slices"
//line set.go2:5
 "sort"
//line set.go2:5
 "testing"
//line set.go2:5
)

//line set.go2:5
type Importable୦ int
//line set.go2:5
type _ math.Importable୦
//line set.go2:5
type _ slices.Importable୦
//line set.go2:5
type _ sort.Float64Slice

//line set.go2:5
var _ = testing.AllocsPerRun
