// Code generated by go2go; DO NOT EDIT.


//line set.go2:1
package sets

import "github.com/changkun/go2generics/contracts"

//line set.go2:3
type Importable୦ int
//line set.go2:3
type _ contracts.Importable୦
