// Code generated by go2go; DO NOT EDIT.


//line errors.go2:6
package errors

//line errors.go2:6
import "testing"

//line errors.go2:6
type Importable୦ int

//line errors.go2:6
var _ = testing.AllocsPerRun
