// Code generated by go2go; DO NOT EDIT.


//line bug2_test.go2:1
package bugs

//line bug2_test.go2:1
import (
//line bug2_test.go2:1
 "runtime"
//line bug2_test.go2:1
 "sync/atomic"
//line bug2_test.go2:1
 "testing"
//line bug2_test.go2:1
)

//line bug2_test.go2:12
func TestFuture(t *testing.T) {
	s := "done"
	f := instantiate୦୦Future୦string{}
	f.Put(s)

	if f.Get() != s {
		t.Fatalf("future failed")
	}
}

//line bug2_test.go2:20
type instantiate୦୦Future୦string struct {
//line bug2.go2:11
 value atomic.Value
}

func (f *instantiate୦୦Future୦string,) Get() string {
	var v interface{}
	for ; v == nil; v = f.value.Load() {
		runtime.Gosched()
	}
	return v.(string)
}

func (f *instantiate୦୦Future୦string,) Put(v string,

//line bug2.go2:22
) {
	f.value.Store(interface{}(v))
}

//line bug2.go2:24
var _ = runtime.BlockProfile
//line bug2.go2:24
var _ = atomic.AddInt32
//line bug2.go2:24
var _ = testing.AllocsPerRun
