// Code generated by go2go; DO NOT EDIT.


//line bug2_test.go2:1
package bugs

import (
	"testing"
)

//line bug2_test.go2:10
func TestFuture(t *testing.T) {
	s := "done"
	f := instantiate୦୦Future୦string{}
	f.Put(s)

	if f.Get() != s {
		t.Fatalf("future failed")
	}
}

//line bug2_test.go2:18
type instantiate୦୦Future୦string struct {
//line bug2.go2:11
 value atomic.Value
}

func (f *instantiate୦୦Future୦string,) Get() string {
	var v interface{}
	for ; v == nil; v = f.value.Load() {
		runtime.Gosched()
	}
	return v.(string)
}

func (f *instantiate୦୦Future୦string,) Put(v string,

//line bug2.go2:22
) {
	f.value.Store(interface{}(v))
}

//line bug2.go2:24
type _ testing.B
