// Code generated by go2go; DO NOT EDIT.


//line bug2.go2:1
package bugs

//line bug2.go2:1
import (
//line bug2.go2:1
 "runtime"
//line bug2.go2:1
 "sync/atomic"
//line bug2.go2:1
 "testing"
//line bug2.go2:1
)

//line bug2.go2:1
type Importable୦ int

//line bug2.go2:1
var _ = runtime.BlockProfile
//line bug2.go2:1
var _ = atomic.AddInt32
//line bug2.go2:1
var _ = testing.AllocsPerRun
