// Code generated by go2go; DO NOT EDIT.


//line bug2.go2:1
package bugs

import (
	"runtime"
	"sync/atomic"
)

//line bug2.go2:6
type Importable୦ int
//line bug2.go2:6
type _ runtime.BlockProfileRecord
//line bug2.go2:6
type _ atomic.Value
