// Code generated by go2go; DO NOT EDIT.


//line ring.go2:6
package ring

//line ring.go2:6
import (
//line ring.go2:6
 "fmt"
//line ring.go2:6
 "testing"
//line ring.go2:6
)

//line ring.go2:6
type Importable୦ int

//line ring.go2:6
var _ = fmt.Errorf
//line ring.go2:6
var _ = testing.AllocsPerRun
