// Code generated by go2go; DO NOT EDIT.


//line metrics.go2:3
package metrics

//line metrics.go2:3
import (
//line metrics.go2:3
 "sync"
//line metrics.go2:3
 "testing"
//line metrics.go2:3
)

//line metrics.go2:3
type Importable୦ int
//line metrics.go2:3
type _ sync.Cond

//line metrics.go2:3
var _ = testing.AllocsPerRun
