// Code generated by go2go; DO NOT EDIT.


//line metrics_test.go2:5
package metrics

//line metrics_test.go2:5
import (
//line metrics_test.go2:5
 "sync"
//line metrics_test.go2:5
 "testing"
//line metrics_test.go2:5
)

//line metrics_test.go2:9
func TestMetric1(t *testing.T) {
	m := instantiate୦୦Metric1୦int{}

	m.Add(1)
	m.Add(2)
}

func TestMetric2(t *testing.T) {
	m := instantiate୦୦Metric2୦int୦string{}

	m.Add(1, "1")
	m.Add(2, "2")
}

func TestMetric3(t *testing.T) {
	m := instantiate୦୦Metric3୦int୦string୦float64{}

	m.Add(1, "1", 1.0)
	m.Add(2, "2", 2.0)
}

//line metrics_test.go2:28
type instantiate୦୦Metric1୦int struct {
//line metrics.go2:13
 mu sync.Mutex
			m  map[int]int
}

//line metrics.go2:18
func (m *instantiate୦୦Metric1୦int,) Add(v int,

//line metrics.go2:18
) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.m == nil {
		m.m = make(map[int]int)
	}
	m.m[v]++
}

//line metrics.go2:25
type instantiate୦୦Metric2୦int୦string struct {
//line metrics.go2:35
 mu sync.Mutex
	m map[instantiate୦୦pair୦int୦string]int
}

//line metrics.go2:40
func (m *instantiate୦୦Metric2୦int୦string,) Add(v1 int,

//line metrics.go2:40
 v2 string,

//line metrics.go2:40
) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.m == nil {
		m.m = make(map[instantiate୦୦pair୦int୦string]int)
	}
	m.m[instantiate୦୦pair୦int୦string{v1, v2}]++
}

//line metrics.go2:47
type instantiate୦୦Metric3୦int୦string୦float64 struct {
//line metrics.go2:58
 mu sync.Mutex
	m map[instantiate୦୦key3୦int୦string୦float64]int
}

//line metrics.go2:63
func (m *instantiate୦୦Metric3୦int୦string୦float64,) Add(v1 int,

//line metrics.go2:63
 v2 string,

//line metrics.go2:63
 v3 float64,

//line metrics.go2:63
) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.m == nil {
		m.m = make(map[instantiate୦୦key3୦int୦string୦float64]int)
	}
	m.m[instantiate୦୦key3୦int୦string୦float64{v1, v2, v3}]++
}

//line metrics.go2:70
type instantiate୦୦pair୦int୦string struct {
//line metrics.go2:29
 f1 int

//line metrics.go2:30
 f2 string
}
//line metrics.go2:31
type instantiate୦୦key3୦int୦string୦float64 struct {
//line metrics.go2:51
 f1 int

//line metrics.go2:52
 f2 string

//line metrics.go2:53
 f3 float64
}
//line metrics.go2:54
type _ sync.Cond

//line metrics.go2:54
var _ = testing.AllocsPerRun
