// Code generated by go2go; DO NOT EDIT.


//line metrics.go2:7
package metrics

//line metrics.go2:7
import (
//line metrics.go2:7
 "sync"
//line metrics.go2:7
 "testing"
//line metrics.go2:7
)

//line metrics.go2:7
type Importable୦ int
//line metrics.go2:7
type _ sync.Cond

//line metrics.go2:7
var _ = testing.AllocsPerRun
